### ISSUE TITLE
The problem relates to the dataset

### ISSUE THREAD

**Issue by tranquangchung** [nachifur/LLPC#2]
Dear author

First of all, thank you for sharing a useful source code.
The problem "Overlapping Cervical Cell Instance Segmentation" is a domain that I research. And your code can support me a lot in this domain.
If your dataset (CCESD) has not a security policy, could you share it with me that you use in your study?
My email is: bktranquangchung@gmail.com

Looking forward to your reply

Best regards

**Comment by ghost** [comment]
The release of the dataset will take some time. I will  release CCEDD around the end of November. 
**CCEDD is a dataset for edge detection, not for Instance Segmentation.** In other words, CCEDD only includes edge ground truth(corrected+not corrected).
Thank you for your attention to our work.
